config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get 'tasks' => 'tasks#index'           #: get all your tasks.

    get '/tasks/new' => 'tasks#new'         #: get the form to create a new task
    post '/tasks' => 'tasks#create'         #: post a new task

    get '/tasks/:id' => 'tasks#show', as: :task       #: get a precise task, e.g get '/tasks/33' get task with id=3

    get '/tasks/:id/edit' => 'tasks#edit', as: :edit_task   #: get the form to edit an existing task
    patch '/tasks/:id' => 'tasks#update'    #: update an existing task

    delete '/tasks/:id' => 'tasks#destroy'  #: delete an existing task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(user_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(user_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def user_params
    params.require(:task).permit(:name, :description, :target_date, :owner)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :target_date %>
  <%= f.date_field :target_date %>

  <%= f.label :owner %>
  <%= f.text_field :owner %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Update a task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>List of Tasks</h1>
<% @tasks.each do |task| %>
<ul>
  <li>
  <p><%= task.name%></p>
  <p><%= link_to "More Details", task_path(task) %></p>
  <p><%= link_to "Edit", edit_task_path(task) %></p>
  <p><%= link_to "Delete", task_path(task), method: :delete %></p>
  </li>
</ul>
<% end %>

<p><%= link_to "Create new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>Create a task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p><%= @task.description %></p>
<p><%= @task.target_date %></p>
<p><%= @task.owner %></p>
<p><%= @task.created_at %></p>

<p><%= link_to "Back to the list", tasks_path %></p>